name: JSDoc build and deploy

on:
  push:
    branches:
      - 02-solution-study-case
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: 02-solution-study-case

      - name: Build JSDoc
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./assets
          recurse: true
          output_dir: ./out
          config_file: ./assets/jsdoc/conf.json
          template: minami
          front_page: README.md

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
